"""Add insight to leads

Revision ID: 5e11ab8cd099
Revises: aa271074235e
Create Date: 2023-11-11 03:31:18.819470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e11ab8cd099"
down_revision = "aa271074235e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("insight", sa.Column("lead_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "insight", "lead", ["lead_id"], ["id"])
    op.drop_constraint("role_name_key", "role", type_="unique")
    op.drop_index("ix_role_name", table_name="role")
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.create_index("ix_role_name", "role", ["name"], unique=False)
    op.create_unique_constraint("role_name_key", "role", ["name"])
    op.drop_constraint(None, "insight", type_="foreignkey")
    op.drop_column("insight", "lead_id")
    # ### end Alembic commands ###
