"""Add Role and Biosignal related models

Revision ID: aa271074235e
Revises: d4867f3a4c0a
Create Date: 2023-11-08 08:11:13.455575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa271074235e"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True, unique=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_created_at"), "role", ["created_at"], unique=False)
    op.create_index(op.f("ix_role_description"), "role", ["description"], unique=False)
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=False)
    op.create_table(
        "biosignal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_biosignal_created_at"), "biosignal", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_biosignal_id"), "biosignal", ["id"], unique=False)
    op.create_index(op.f("ix_biosignal_name"), "biosignal", ["name"], unique=False)
    op.create_index(
        op.f("ix_biosignal_updated_at"), "biosignal", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_biosignal_user_id"), "biosignal", ["user_id"], unique=False
    )
    op.create_table(
        "insight",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("biosignal_id", sa.Integer(), nullable=True),
        sa.Column("value_1", sa.Float(), nullable=True),
        sa.Column("value_2", sa.Boolean(), nullable=True),
        sa.Column("value_3", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["biosignal_id"],
            ["biosignal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insight_created_at"), "insight", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_insight_description"), "insight", ["description"], unique=False
    )
    op.create_index(op.f("ix_insight_id"), "insight", ["id"], unique=False)
    op.create_index(op.f("ix_insight_name"), "insight", ["name"], unique=False)
    op.create_index(
        op.f("ix_insight_updated_at"), "insight", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_insight_value_1"), "insight", ["value_1"], unique=False)
    op.create_index(op.f("ix_insight_value_2"), "insight", ["value_2"], unique=False)
    op.create_index(op.f("ix_insight_value_3"), "insight", ["value_3"], unique=False)
    op.create_table(
        "lead",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("samples_number", sa.Integer(), nullable=True),
        sa.Column("signal", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("biosignal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["biosignal_id"],
            ["biosignal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_created_at"), "lead", ["created_at"], unique=False)
    op.create_index(op.f("ix_lead_id"), "lead", ["id"], unique=False)
    op.create_index(op.f("ix_lead_name"), "lead", ["name"], unique=False)
    op.create_index(
        op.f("ix_lead_samples_number"), "lead", ["samples_number"], unique=False
    )
    op.create_index(op.f("ix_lead_signal"), "lead", ["signal"], unique=False)
    op.add_column("user", sa.Column("role_id", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_foreign_key(None, "user", "role", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "created_at")
    op.drop_column("user", "role_id")
    op.drop_index(op.f("ix_lead_signal"), table_name="lead")
    op.drop_index(op.f("ix_lead_samples_number"), table_name="lead")
    op.drop_index(op.f("ix_lead_name"), table_name="lead")
    op.drop_index(op.f("ix_lead_id"), table_name="lead")
    op.drop_index(op.f("ix_lead_created_at"), table_name="lead")
    op.drop_table("lead")
    op.drop_index(op.f("ix_insight_value_3"), table_name="insight")
    op.drop_index(op.f("ix_insight_value_2"), table_name="insight")
    op.drop_index(op.f("ix_insight_value_1"), table_name="insight")
    op.drop_index(op.f("ix_insight_updated_at"), table_name="insight")
    op.drop_index(op.f("ix_insight_name"), table_name="insight")
    op.drop_index(op.f("ix_insight_id"), table_name="insight")
    op.drop_index(op.f("ix_insight_description"), table_name="insight")
    op.drop_index(op.f("ix_insight_created_at"), table_name="insight")
    op.drop_table("insight")
    op.drop_index(op.f("ix_biosignal_user_id"), table_name="biosignal")
    op.drop_index(op.f("ix_biosignal_updated_at"), table_name="biosignal")
    op.drop_index(op.f("ix_biosignal_name"), table_name="biosignal")
    op.drop_index(op.f("ix_biosignal_id"), table_name="biosignal")
    op.drop_index(op.f("ix_biosignal_created_at"), table_name="biosignal")
    op.drop_table("biosignal")
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_index(op.f("ix_role_description"), table_name="role")
    op.drop_index(op.f("ix_role_created_at"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
